### ISSUE TITLE
What are these title mean?

### ISSUE THREAD

**Issue by SuoJianfei** [jenkinsci/osf-builder-suite-for-sfcc-credentials-plugin#2]
Hi Dear,
Could you please add some notes to these parameters?
What should I input? 
Cause I'm new to this stuff, Need Help PLZ!

I have files like .key .pem .req .

Thanks a lot!!!
![image](https://user-images.githubusercontent.com/51899685/91545910-49a07a80-e954-11ea-88bc-08f701b633b6.png)

**Comment by danechitoaie** [comment]
Hi,
Starting from the ZIP file with the server certificates that SFCC will give you when they setup the primary instance group you can follow this guide https://plugins.jenkins.io/osf-builder-suite-for-sfcc-credentials/ on how to generate the client certificate and private key.

After you generate the client cert/key you will have to copy & paste the contents of the following files:

- In `Server Certificate` text-box copy and paste the contents of `cert.merchant.sitename.net_01.crt`
- In `Client Certificate` text-box copy and paste the contents of `$user.pem`
- In `Client Private Key` text-box copy and paste the contents of `$user.key`

`$user.pem` and `$user.key` are the files that you create by following the guide at the link above. `cert.merchant.sitename.net_01.crt` will already be there in the ZIP file you receive from SFCC.

**Comment by SuoJianfei** [comment]
Dear,
So clear and simple.
It works perfectly! Thank you so much!!!!!!!!!!!!!!!!!!!!!!
